language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-phonestrap' ]; then cd .. && eval "mv $currentfolder generator-phonestrap" && cd generator-phonestrap; fi

